plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

ext {
    set('springAiVersion', '1.0.0')
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}